SELECT
 event.ENCOUNTER_ID ,
 event.CURRENT_DEPT_ID AS '当前科室编码',
 event.CURRENT_DEPT_NAME AS '当前科室',
    event.PERSON_NAME AS '患者姓名',
 event.IMRN AS '住院号',
 event.CURRENT_ADMITTER_NAME AS '责任医师',
 team.ORG_NAME as "TEAM_NAME",
 team.ORG_ID as "TEAM_ID",
  team.ORG_NO as "TEAM_NO",
 team.ORG_NAME as "当前医疗组",
 event.ADMITTED_TO_WARD_AT AS '入区时间',
 event.WARD_DISCHARGED_AT AS '出区时间',
 event.FIRST_ORDER_AT as '首次医嘱开立时间',
 DATEDIFF(HOUR,event.ADMITTED_TO_WARD_AT,event.FIRST_ORDER_AT)  AS '首次医嘱开立时间-入院时间',
 CASE WHEN ROUND_WITHIN_EIGHT_HOUR = '98175' THEN '是' ELSE '否' END AS '是否入院8小时内开具检查或治疗医嘱',
 CASE WHEN ROUND_WITHIN_EIGHT_HOUR = '98175' THEN 98175 ELSE 98176 END AS "standFlag"
FROM
 MRAS_BUSINESS_WARDROUND event  WITH (NOLOCK)
  LEFT JOIN INPATIENT_ENCOUNTER inp WITH (NOLOCK)  ON event.ENCOUNTER_ID = inp.ENCOUNTER_ID
 LEFT JOIN MRAS_ORGANIZATION team WITH (NOLOCK)  ON team.ORG_ID = inp.CURRENT_MEDICAL_GROUP_ID
WHERE
 --布局组件设置提升效率
     event.ADMITTED_TO_WARD_AT BETWEEN :marptBeginAt and :marptEndAt
