SELECT
event.ENCOUNTER_ID ,
event.ENCOUNTER_ID AS "ROWNUM",
event.CURRENT_DEPT_ID AS "当前科室编码",
event.CURRENT_DEPT_NAME AS "当前科室",
event.IMRN AS "住院号",
event.PERSON_NAME AS "患者姓名",
event.CURRENT_ADMITTER_NAME AS "责任医师",
team.ORG_NAME as "TEAM_NAME",
team.ORG_ID as "TEAM_ID",
team.ORG_NO as "TEAM_NO",
team.ORG_NAME as "当前医疗组",
event.ADMITTED_TO_WARD_AT AS "入区时间",
event.WARD_DISCHARGED_AT AS "出区时间",
t1.INPAT_TRANSFER_AT AS "转科时间",
DATEDIFF(HOUR,event.ADMITTED_TO_WARD_AT,t1.INPAT_TRANSFER_AT)  AS "转科时间-入院时间",
o1.ORG_NAME AS "转出科室",
o2.ORG_NAME AS "转入科室",
CASE WHEN  (TRANSFER_WITHIN_TWO_DAY = 98175 AND  DATEDIFF(HOUR,event.ADMITTED_TO_WARD_AT,t1.INPAT_TRANSFER_AT) < 48) THEN '是' ELSE '否' END AS "是否48小时内转科" ,
CASE WHEN  (TRANSFER_WITHIN_TWO_DAY = 98175 AND  DATEDIFF(HOUR,event.ADMITTED_TO_WARD_AT,t1.INPAT_TRANSFER_AT) < 48) THEN 98175 ELSE 98175 END AS "standFlag"
FROM
MRAS_BUSINESS_FIRSTVISIT event  WITH (NOLOCK)
LEFT JOIN INPAT_TRANSFER t1  WITH (NOLOCK)  ON event.ENCOUNTER_ID = t1.ENCOUNTER_ID
  LEFT JOIN ORGANIZATION o1  WITH (NOLOCK)   ON t1.ORIGIN_DEPT_ID = o1.ORG_ID
  LEFT JOIN ORGANIZATION o2  WITH (NOLOCK)  ON t1.DESTINATION_DEPT_ID = o2.ORG_ID
LEFT JOIN INPATIENT_ENCOUNTER inp WITH (NOLOCK)  ON event.ENCOUNTER_ID = inp.ENCOUNTER_ID
LEFT JOIN MRAS_ORGANIZATION team WITH (NOLOCK)  ON team.ORG_ID = inp.CURRENT_MEDICAL_GROUP_ID
WHERE
--布局组件设置提升效率
 event.ADMITTED_TO_WARD_AT BETWEEN :marptBeginAt and :marptEndAt
AND t1.INPAT_TRANSFER_ID IS NOT NULL
AND (t1.INPAT_TRANSFER_TYPE_CODE = '399549991' OR (t1.INPAT_TRANSFER_TYPE_CODE = '399549990' AND t1.ORIGIN_DEPT_ID <> t1.DESTINATION_DEPT_ID))
AND t1.IS_DEL = 0
AND event.VERSION = 'V2.0'
AND event.IS_DEL = 0
