SELECT
event.MRAS_INDEX_ENCOUNTER_ID as ENCOUNTER_ID,
event.MRAS_DIM_DEPT_NAME AS 当前科室,
b.PERSON_NAME AS 患者姓名,
b.BIZ_ATTR_ONE_NO AS 住院号,
b.EMPLOYEE_NAME AS 责任医师,
team.ORG_NAME as "TEAM_NAME",
team.ORG_ID as "TEAM_ID",
team.ORG_NO as "TEAM_NO",
team.ORG_NAME as "当前医疗组",
b.EVENT_AT AS 入区时间,
b.EVENT_END_AT AS 出区时间,
event.SURG_NAME AS 手术名称,
event.SURG_LEVEL AS 手术等级,
event.SURG_START as 手术开始时间,
event.SURG_END as 手术结束时间,
CASE WHEN INTRA_BLOOD_FLAG = 98175 THEN '是' ELSE '否' END AS 是否进行术中输血,
CASE WHEN AUTOLOGOUS_BLOOD_TRANS_FLAG = 98175 THEN '是' ELSE '否' END AS 是否自体血回输,
CASE WHEN AUTOLOGOUS_BLOOD_TRANS_FLAG = 98175 THEN 98175 ELSE 98176 END AS "standFlag"
FROM
MRAS_INDEX_SURGREC event WITH (NOLOCK)
inner join MRAS_PATIENT_EVENT b WITH (NOLOCK) on event.MRAS_INDEX_ENCOUNTER_ID = b.ENCOUNTER_ID and b.EVENT_NO = 'PatientRecord' and b.IS_DEL=0
LEFT JOIN INPATIENT_ENCOUNTER inp WITH (NOLOCK)  ON event.MRAS_INDEX_ENCOUNTER_ID = inp.ENCOUNTER_ID
LEFT JOIN MRAS_ORGANIZATION team WITH (NOLOCK)  ON team.ORG_ID = inp.CURRENT_MEDICAL_GROUP_ID
WHERE
--布局组件设置提升效率
    AND event.SURG_END BETWEEN :start_time and :end_time
AND event.IS_DEL = 0
AND event.INTRA_BLOOD_FLAG = 98175
