select t1.ENCOUNTER_ID
AS bizId,
--用来更新数据
t1.FIRST_ADMITTED_TO_WARD_AT
AS eventAt,
-- 预留
'1' AS mrasTargetDefinitionId,
'V2.0' as version,
GETDATE()
AS extractAt,
t1.ENCOUNTER_ID
AS encounterId,
t1.FULL_NAME
AS personName,
t1.IMRN
as imrn,
t1.CURRENT_DEPT_ID
AS currentDeptId,
o1.ORG_NAME
AS currentDeptName,
t1.CURRENT_WARD_ID
AS currentWardId,
o2.ORG_NAME
AS currentWardName,
t1.FIRST_ADMITTED_TO_WARD_AT
AS admittedToWardAt,
t1.DISCHARGED_FROM_WARD_AT
AS wardDischargedAt,
t3.EMPLOYEE_ID
AS currentAdmitterId,
t4.EMPLOYEE_NAME
AS currentAdmitterName,
t1.HOSPITAL_SOID
AS hospitalSoid,
t1.SOURCE_HOSPITAL_AREA_ID
AS hospitalAreaId,
C.TOTAL_COST
as totalCost,--费用
t6.CREATED_AT
AS emrCreatedAt,--疑难病历讨论时间
t6.INP_EMR_SET_CREATED_AT
AS emrSetSubmitAt,--疑难病历讨论提交时间
CASE WHEN t1.IS_DEL = '1' THEN 1 ELSE 0 END AS isDel,
CASE
WHEN t6.INP_EMR_SET_ID IS NOT NULL THEN 98175
ELSE 98176 END
AS highCostDifficultDiscussion,--高额异常费用患者进行疑难病例讨论的占比
''
AS memo
from INPATIENT_ENCOUNTER t1
INNER JOIN MAHP_MAIN B ON t1.ENCOUNTER_ID = B.ENCOUNTER_ID AND B.MAHP_STATUS = 958566 AND B.IS_DEL = 0
INNER JOIN MAHP_COST C ON C.MAHP_ID = B.MAHP_ID AND C.IS_DEL = 0
left join (select A.*, ROW_NUMBER() OVER (PARTITION BY A.ENCOUNTER_ID ORDER BY A.CREATED_AT DESC ) AS rn
from INPATIENT_EMR_SET A
where A.IS_DEL = 0
and A.INP_MRT_MONITOR_ID = 125044678493294634) t6 on t1.ENCOUNTER_ID=t6.ENCOUNTER_ID and t6.rn=1
LEFT JOIN ORGANIZATION o1 ON t1.CURRENT_DEPT_ID = o1.ORG_ID
LEFT JOIN ORGANIZATION o2 ON t1.CURRENT_WARD_ID = o2.ORG_ID
LEFT JOIN INPATIENT_PARTICIPANT t3 ON t1.ENCOUNTER_ID = t3.ENCOUNTER_ID AND t3.IS_DEL = 0 AND t3.INPAT_PARTICIPANT_TYPE_CODE = 1000098
LEFT JOIN EMPLOYEE_INFO t4 ON t3.EMPLOYEE_ID = t4.EMPLOYEE_ID and t4.IS_DEL=0
where t1.IS_DEL=0 and C.TOTAL_COST > 200000
  AND t1.ENCOUNTER_ID in (select ENCOUNTER_ID from INPATIENT_ENCOUNTER where DISCHARGED_FROM_WARD_AT BETWEEN :start_time and :end_time)
