SELECT a.*,
t6.INP_EMR_SET_CREATED_AT AS preopMdtCompletedAt,
CASE WHEN t6.INP_EMR_SET_ID IS NOT NULL THEN 98175 ELSE 98176 END AS preopMdtCompleted,
145235 AS encounterTypeCode,
0 AS mrasBusinessIndexId,
'V2.0' AS version
FROM (
SELECT
t1.CLI_ORDER_ITEM_ID AS bizId,
t1.SURGERY_END_AT AS eventAt,
GETDATE() AS extractAt,
'1' AS mrasTargetDefinitionId,
t1.ENCOUNTER_ID AS encounterId,
t2.PERSON_NAME AS personName,
t2.BIZ_ATTR_ONE_NO AS imrn,
t2.DEPT_ID AS currentDeptId,
t2.DEPT_NAME AS currentDeptName,
t2.WARD_ID AS currentWardId,
t2.WARD_NAME AS currentWardName,
t2.EVENT_AT AS admittedToWardAt,
t2.EVENT_END_AT AS dischargedFromWardAt,
t2.EMPLOYEE_NAME AS currentAdmitterName,
t11.SURGERY_ID AS surgeryId,
t11.SURGERY_NAME AS surgName,
t11.SURGERY_GRADE_CODE AS surgLevelCode,
s4.VALUE_DESC AS surgLevelName,
CASE WHEN t1.SURGERY_START_AT IS NULL THEN t1.PLANNED_SURGERY_DATE ELSE t1.SURGERY_START_AT END AS surgeryStartAt,
t1.SURGERY_END_AT AS surgeryEndAt,
case when b.DISCHARGE_TYPE_CODE = 136924 then 98175 else 98176 end as deathFlag,
case when b.DISCHARGE_TYPE_CODE = 136924 then b.DISCHARGED_AT else null end as deathAt,
t2.HOSPITAL_SOID AS hospitalSOID,
t1.IS_DEL AS isDel,
CASE WHEN t11.SURGERY_GRADE_CODE = 136619 THEN
(SELECT TOP 1 a1.INP_EMR_SET_ID FROM INPATIENT_EMR_SET a1
    WHERE a1.ENCOUNTER_ID = t1.ENCOUNTER_ID AND DATEDIFF(HOUR, a1.CREATED_AT, ISNULL(t1.SURGERY_START_AT, t1.PLANNED_SURGERY_DATE)) <= 48
    AND a1.INP_MRT_MONITOR_ID=125044678493294640 AND a1.INP_EMR_SET_TITLE LIKE '%多学科%' AND a1.IS_DEL = 0 AND a1.INP_EMR_STATUS NOT IN (960074,390030405)
    ORDER BY a1.INP_EMR_SET_CREATED_AT DESC)
ELSE NULL END AS INP_EMR_SET_ID
FROM INP_SURGICAL_PLAN t1
INNER JOIN MRAS_PATIENT_EVENT t2 ON t1.ENCOUNTER_ID = t2.ENCOUNTER_ID AND t2.EVENT_NO = 'PatientRecord' AND t2.IS_DEL = 0
INNER JOIN (
    SELECT t.CLI_ORDER_ITEM_ID,
MAX(t.SURGERY_ID) AS SURGERY_ID,
MAX(t.SURGERY_GRADE_CODE) AS SURGERY_GRADE_CODE,
LEFT(STUFF((
SELECT ',' + t2.SURGERY_NAME
FROM (
SELECT DISTINCT isa.CLI_ORDER_ITEM_ID, isa.SURGERY_ID, cs.SURGERY_GRADE_CODE, isa.SURGERY_NAME, isa.SURGICAL_ANESTHESIA_CODE
FROM INP_SURGICAL_ANESTHESIA_PLAN isa
INNER JOIN CLIBASIC_SURGERY cs ON isa.CS_ID = cs.CLIBASIC_SURGERY_ID AND cs.SURGERY_DIR_NO IN ('957348', '957347')
WHERE isa.IS_DEL = 0 AND isa.SURGERY_NAME IS NOT NULL
) t2
WHERE t2.CLI_ORDER_ITEM_ID = t.CLI_ORDER_ITEM_ID
ORDER BY t2.SURGERY_NAME
FOR XML PATH('')
), 1, 1, ''), 1999) AS SURGERY_NAME,
MAX(t.SURGICAL_ANESTHESIA_CODE) AS ANES_TYPE_ID
    FROM (
SELECT DISTINCT isa.CLI_ORDER_ITEM_ID, isa.SURGERY_ID, cs.SURGERY_GRADE_CODE, isa.SURGERY_NAME AS SURGERY_NAME, isa.SURGICAL_ANESTHESIA_CODE
FROM INP_SURGICAL_ANESTHESIA_PLAN isa
INNER JOIN CLIBASIC_SURGERY cs ON isa.CS_ID = cs.CLIBASIC_SURGERY_ID AND cs.SURGERY_DIR_NO IN ('957348', '957347')
WHERE isa.IS_DEL = 0 AND isa.SURGERY_NAME IS NOT NULL
    ) t
    GROUP BY t.CLI_ORDER_ITEM_ID
) t11 ON t1.CLI_ORDER_ITEM_ID = t11.CLI_ORDER_ITEM_ID
LEFT join MAHP_DMTS_MAIN b on t1.ENCOUNTER_ID = b.ENCOUNTER_ID and b.IS_DEL = 0
LEFT JOIN VALUE_SET s4 ON t11.SURGERY_GRADE_CODE = s4.VALUE_ID AND s4.CODE_SYSTEM_ID = 64655
WHERE 1 = 1 AND t11.SURGERY_GRADE_CODE IN (136618, 136619)
AND t2.EVENT_END_AT BETWEEN :startTime and :endTime
) a
LEFT JOIN INPATIENT_EMR_SET t6 on a.INP_EMR_SET_ID = t6.INP_EMR_SET_ID
