SELECT
t1.CLI_ORDER_ITEM_ID AS bizId,  --用来更新数据
  t1.SURGERY_START_AT AS eventAt, -- 预留
  GETDATE() AS extractAt,
'1' AS mrasBusinessIndexId,
'1' AS mrasTargetDefinitionId,
'V2.0' as version,
  t1.ENCOUNTER_ID AS encounterId,
  t12.FULL_NAME AS personName,
  t12.IMRN as imrn,
  t12.CURRENT_DEPT_ID AS deptId,
  o1.ORG_NAME AS deptName,
  t12.CURRENT_WARD_ID AS wardId,
  o2.ORG_NAME AS wardName,
  t12.ADMITTED_TO_WARD_AT AS admittedToWardAt,
  t12.DISCHARGED_FROM_WARD_AT AS dischargedFromWardAt,
  t13.EMPLOYEE_ID AS employeeId,
  t14.EMPLOYEE_NAME AS employeeName,
  t12.HOSPITAL_SOID AS hospitalSoid,
  t12.SOURCE_HOSPITAL_AREA_ID AS hospitalAreaId,
  CASE WHEN t1.IS_DEL = '1'  THEN 1 ELSE 0 END AS isDel,
  t1.SURGERY_START_AT AS surgeryStartAt,
t1.SURGERY_END_AT AS surgeryEndAt,
t11.SURGERY_NAME,
-- 主刀医师是否重复
    CASE WHEN EXISTS (
SELECT 1
FROM INP_SURGICAL_PLAN t2
LEFT JOIN (
SELECT aa.CLI_ORDER_ID, MAX(ab.SURGEON_ID) AS OPERATOR_ID
FROM INP_SURGICAL_ORDER_ITEM aa
LEFT JOIN INP_SURGICAL_OPERATOR_PLAN ab ON aa.CLI_ORDER_ITEM_ID=ab.CLI_ORDER_ITEM_ID AND ab.SURGICAL_OPERATOR_ROLE_CODE = 399010952 AND ab.IS_DEL=0
WHERE aa.IS_DEL=0
GROUP BY aa.CLI_ORDER_ID
) t20 ON t2.CLI_ORDER_ID = t20.CLI_ORDER_ID
WHERE t20.OPERATOR_ID = t10.OPERATOR_ID
AND t2.CLI_ORDER_ID <> t1.CLI_ORDER_ID
AND t2.SURGERY_START_AT < t1.SURGERY_END_AT
AND t2.SURGERY_END_AT > t1.SURGERY_START_AT
    ) THEN 98175 ELSE 98176 END AS OPERATOR_OVERLAP,
    -- 麻醉医师 是否重复
    CASE WHEN EXISTS (
SELECT 1
FROM INP_SURGICAL_PLAN t3
LEFT JOIN (
SELECT aa.CLI_ORDER_ID, MAX(ae.SURGEON_ID) AS ANES_DOCT_ID
FROM INP_SURGICAL_ORDER_ITEM aa
LEFT JOIN INP_SURGICAL_OPERATOR_PLAN ae ON aa.CLI_ORDER_ITEM_ID=ae.CLI_ORDER_ITEM_ID AND ae.SURGICAL_OPERATOR_ROLE_CODE = 399010958 AND ae.IS_DEL=0
WHERE aa.IS_DEL=0
GROUP BY aa.CLI_ORDER_ID
) t30 ON t3.CLI_ORDER_ID = t30.CLI_ORDER_ID
WHERE t30.ANES_DOCT_ID = t10.ANES_DOCT_ID
AND t3.CLI_ORDER_ID <> t1.CLI_ORDER_ID
AND t3.SURGERY_START_AT < t1.SURGERY_END_AT
AND t3.SURGERY_END_AT > t1.SURGERY_START_AT
    ) THEN 98175 ELSE 98176 END AS ANES_DOCT_OVERLAP,
    -- 主刀医师重复的另外一个手术CLI_ORDER_ITEM_ID
    STUFF((
SELECT ',' + CAST(t2.CLI_ORDER_ITEM_ID AS VARCHAR(50))
FROM INP_SURGICAL_PLAN t2
LEFT JOIN (
SELECT aa.CLI_ORDER_ID, MAX(ab.SURGEON_ID) AS OPERATOR_ID
FROM INP_SURGICAL_ORDER_ITEM aa
LEFT JOIN INP_SURGICAL_OPERATOR_PLAN ab ON aa.CLI_ORDER_ITEM_ID=ab.CLI_ORDER_ITEM_ID AND ab.SURGICAL_OPERATOR_ROLE_CODE = 399010952 AND ab.IS_DEL=0
WHERE aa.IS_DEL=0
GROUP BY aa.CLI_ORDER_ID
) t20 ON t2.CLI_ORDER_ID = t20.CLI_ORDER_ID
WHERE t20.OPERATOR_ID = t10.OPERATOR_ID
AND t2.CLI_ORDER_ID <> t1.CLI_ORDER_ID
AND t2.SURGERY_START_AT < t1.SURGERY_END_AT
AND t2.SURGERY_END_AT > t1.SURGERY_START_AT
FOR XML PATH('')
    ), 1, 1, '') AS OVERLAP_OPERATOR_SURGERIES,
    -- 麻醉医师重复的另外一个手术CLI_ORDER_ITEM_ID
    STUFF((
SELECT ',' + CAST(t3.CLI_ORDER_ITEM_ID AS VARCHAR(50))
FROM INP_SURGICAL_PLAN t3
LEFT JOIN (
SELECT aa.CLI_ORDER_ID, MAX(ae.SURGEON_ID) AS ANES_DOCT_ID
FROM INP_SURGICAL_ORDER_ITEM aa
LEFT JOIN INP_SURGICAL_OPERATOR_PLAN ae ON aa.CLI_ORDER_ITEM_ID=ae.CLI_ORDER_ITEM_ID AND ae.SURGICAL_OPERATOR_ROLE_CODE = 399010958 AND ae.IS_DEL=0
WHERE aa.IS_DEL=0
GROUP BY aa.CLI_ORDER_ID
) t30 ON t3.CLI_ORDER_ID = t30.CLI_ORDER_ID
WHERE t30.ANES_DOCT_ID = t10.ANES_DOCT_ID
AND t3.CLI_ORDER_ID <> t1.CLI_ORDER_ID
AND t3.SURGERY_START_AT < t1.SURGERY_END_AT
AND t3.SURGERY_END_AT > t1.SURGERY_START_AT
FOR XML PATH('')
    ), 1, 1, '') AS OVERLAP_ANES_DOCT_SURGERIES,
   t15.ORG_ID as bizAttrOneId,
   t15.ORG_NAME as bizAttrOneName
FROM INP_SURGICAL_PLAN t1
LEFT JOIN (
SELECT aa.CLI_ORDER_ID, MAX(ab.SURGEON_ID) AS OPERATOR_ID, MAX(ae.SURGEON_ID) AS ANES_DOCT_ID
    FROM INP_SURGICAL_ORDER_ITEM aa
LEFT JOIN INP_SURGICAL_OPERATOR_PLAN ab ON aa.CLI_ORDER_ITEM_ID=ab.CLI_ORDER_ITEM_ID AND ab.SURGICAL_OPERATOR_ROLE_CODE = 399010952 AND ab.IS_DEL=0
LEFT JOIN INP_SURGICAL_OPERATOR_PLAN ae ON aa.CLI_ORDER_ITEM_ID=ae.CLI_ORDER_ITEM_ID AND ae.SURGICAL_OPERATOR_ROLE_CODE = 399010958 AND ae.IS_DEL=0
    WHERE aa.IS_DEL=0
GROUP BY aa.CLI_ORDER_ID
) t10 on t1.CLI_ORDER_ID = t10.CLI_ORDER_ID
LEFT JOIN (
SELECT
    t.CLI_ORDER_ITEM_ID,
STUFF((
SELECT ',' + t2.SURGERY_NAME
FROM (
SELECT DISTINCT isa.CLI_ORDER_ITEM_ID, isa.SURGERY_NAME
FROM INP_SURGICAL_ANESTHESIA_PLAN isa
WHERE isa.IS_DEL = 0
AND isa.SURGERY_NAME IS NOT NULL
AND isa.CLI_ORDER_ITEM_ID IS NOT NULL
AND EXISTS (
SELECT 1
FROM CLIBASIC_SURGERY cs
WHERE cs.SURGERY_DIR_NO IN ('957347','957348')
AND isa.ICD9_CM3_CODE = cs.SURGERY_NO
)
AND isa.CLI_ORDER_ITEM_ID = t.CLI_ORDER_ITEM_ID
) t2
ORDER BY t2.SURGERY_NAME
FOR XML PATH('')
    ), 1, 1, '') AS SURGERY_NAME,
    MAX(t.SURGICAL_ANESTHESIA_CODE) AS ANES_TYPE_ID
FROM (
    SELECT DISTINCT isa.CLI_ORDER_ITEM_ID, isa.SURGERY_NAME, isa.SURGICAL_ANESTHESIA_CODE
    FROM INP_SURGICAL_ANESTHESIA_PLAN isa
    WHERE isa.IS_DEL = 0
AND isa.SURGERY_NAME IS NOT NULL
AND isa.CLI_ORDER_ITEM_ID IS NOT NULL
-- 只要手术，介入治疗这两种类型的
AND EXISTS (SELECT 1 FROM CLIBASIC_SURGERY cs WHERE cs.SURGERY_DIR_NO IN ('957347','957348') AND isa.ICD9_CM3_CODE = cs.SURGERY_NO )
) t
GROUP BY t.CLI_ORDER_ITEM_ID
) t11 on t1.CLI_ORDER_ITEM_ID = t11.CLI_ORDER_ITEM_ID
LEFT JOIN INPATIENT_ENCOUNTER t12 ON t1.ENCOUNTER_ID = t12.ENCOUNTER_ID
LEFT JOIN ORGANIZATION o1 ON t12.CURRENT_DEPT_ID = o1.ORG_ID
LEFT JOIN ORGANIZATION o2 ON t12.CURRENT_WARD_ID = o2.ORG_ID
-- 责任医生
LEFT JOIN INPATIENT_PARTICIPANT t13 ON t12.ENCOUNTER_ID = t13.ENCOUNTER_ID AND  t13.IS_DEL = 0 AND  t13.INPAT_PARTICIPANT_TYPE_CODE = 1000098
LEFT JOIN EMPLOYEE_INFO t14 ON t13.EMPLOYEE_ID = t14.EMPLOYEE_ID
left join (select ei.EMPLOYEE_ID,oxe.ORG_ID,oxeog.ORG_NAME from EMPLOYEE_INFO ei
LEFT JOIN ORGANIZATION_X_EMPLOYEE oxe on ei.EMPLOYEE_ID = oxe.EMPLOYEE_ID AND oxe.IS_DEL = 0 and ORGANIZATION_X_EMPLOYEE_TYPE = 399566319
left join ORGANIZATION oxeog on oxe.ORG_ID = oxeog.ORG_ID) t15 on t15.EMPLOYEE_ID = t10.OPERATOR_ID
WHERE t11.CLI_ORDER_ITEM_ID IS NOT NULL
AND t1.ENCOUNTER_ID in (select ENCOUNTER_ID from INPATIENT_ENCOUNTER where DISCHARGED_FROM_WARD_AT BETWEEN :start_time and :end_time)
