select t1.ENCOUNTER_ID
AS bizId,
--用来更新数据
t1.SCHEDULED_AT
AS eventAt,
-- 预留
'1' AS mrasTargetDefinitionId,
'V2.0' as version,
GETDATE()
AS extractAt,
t1.ENCOUNTER_ID
AS encounterId,
t1.ENCOUNTER_TYPE_CODE   as encounterTypeCode,
R.FULL_NAME
AS personName,
R.OMRN
as imrn,
t1.ENC_DEPT_ID
AS currentDeptId,
o1.ORG_NAME
AS currentDeptName,
t1.SCHEDULED_AT
AS admittedToWardAt,
t1.SCHEDULED_DOCTOR_ID
AS currentAdmitterId,
t4.EMPLOYEE_NAME
AS currentAdmitterName,
t1.HOSPITAL_SOID
AS hospitalSoid,
t1.HOSPITAL_AREA_ID
AS hospitalAreaId,
t2.PRESCRIBED_AT
AS firstOrderAt,--会诊后医嘱开立时间
A.APPLY_CONSULT_EMPLOYEE_NAME
as applyConsultEmployeeName,--发起医师
A.APPLY_CONSULT_AT
AS applyConsultAt,--会诊发起时间
C.SIGNED_AT
AS signedAt,--会诊签到时间
D.CONSULT_COMPLETED_AT
AS finishAt,--会诊完成时间
t5.INP_EMR_SET_CREATED_AT
AS firstEmrSetSubmitAt,--会诊病历完成时间
A.CONSULT_LEVEL_CODE
AS courseLevelCode,--会诊等级
t6.EMPLOYEE_NAME
AS prescribingDoctorName,--医嘱开立医生
t2.CLI_ORDER_ITEM_CONTENT
AS orderName,--医嘱名称
A.CONSULT_STATUS_CODE
AS courseStatus,--会诊状态
CASE WHEN t1.IS_DEL = '1' THEN 1 ELSE 0 END AS isDel,
CASE
WHEN DATEDIFF(minute, A.APPLY_CONSULT_AT, C.SIGNED_AT) < 10 and A.CONSULT_LEVEL_CODE = 977578 THEN 98175
ELSE 98176 END
AS emergencyConsultTimely,--急会诊及时到位率
CASE
WHEN DATEDIFF(minute, D.CONSULT_COMPLETED_AT, t2.PRESCRIBED_AT) < 40 and A.CONSULT_LEVEL_CODE = 977578 THEN 98175
ELSE 98176 END
AS emergencyConsultEffective,--急会诊有效率
CASE
WHEN DATEDIFF(hour, A.APPLY_CONSULT_AT, t5.INP_EMR_SET_CREATED_AT) < 24 and A.CONSULT_LEVEL_CODE = 977577 THEN 98175
ELSE 98176 END
AS regularConsultTimely,--普通会诊及时完成率
CASE
WHEN DATEDIFF(hour, D.CONSULT_COMPLETED_AT, t2.PRESCRIBED_AT) < 24 and A.CONSULT_LEVEL_CODE = 977577 THEN 98175
ELSE 98176 END
AS regularConsultEffective,--普通会诊及时完成率
''
AS memo
FROM OUTPATIENT_ENCOUNTER t1
inner join INPATIENT_CONSULT_APPLY A on t1.ENCOUNTER_ID = A.ENCOUNTER_ID AND A.IS_DEL = 0
left join OUTPATIENT_RECORD R on t1.ENCOUNTER_ID = R.ENCOUNTER_ID AND R.IS_DEL=0
left JOIN (select A.INP_CONSULT_APPLY_ID,B.PRESCRIBED_AT,B.PRESCRIBING_DOCTOR_ID,I.*,
ROW_NUMBER() OVER (PARTITION BY A.ENCOUNTER_ID ORDER BY B.PRESCRIBED_AT ASC) AS rn
from INPATIENT_CONSULT_APPLY A
left join CLINICAL_ORDER B on A.ENCOUNTER_ID = B.ENCOUNTER_ID
inner join CLINICAL_ORDER_ITEM I on I.CLI_ORDER_ID = B.CLI_ORDER_ID
where B.PRESCRIBED_AT > A.CONSULT_COMPLETED_AT) t2
on A.INP_CONSULT_APPLY_ID = t2.INP_CONSULT_APPLY_ID and t2.rn = 1
left join (select INP_CONSULT_APPLY_ID, min(SIGNED_AT) as SIGNED_AT
from INP_CONSULT_INVITATION
where IS_DEL = 0
group by INP_CONSULT_APPLY_ID) C on A.INP_CONSULT_APPLY_ID = C.INP_CONSULT_APPLY_ID
left join (select INP_CONSULT_APPLY_ID, max(CREATED_AT) as CONSULT_COMPLETED_AT
from INPATIENT_CONSULT_REPLY
where IS_DEL = 0
group by INP_CONSULT_APPLY_ID) D on A.INP_CONSULT_APPLY_ID = D.INP_CONSULT_APPLY_ID
left join INPATIENT_EMR_SET t5 on A.INP_EMR_SET_ID=t5.INP_EMR_SET_ID and t5.IS_DEL=0
LEFT JOIN ORGANIZATION o1 ON t1.ENC_DEPT_ID = o1.ORG_ID
LEFT JOIN EMPLOYEE_INFO t4 ON t1.SCHEDULED_DOCTOR_ID = t4.EMPLOYEE_ID
LEFT JOIN EMPLOYEE_INFO t6 ON t2.PRESCRIBING_DOCTOR_ID = t6.EMPLOYEE_ID
WHERE 1 = 1 AND A.CONSULT_STATUS_CODE <> 399329839
 AND t1.ENCOUNTER_ID in (select ENCOUNTER_ID from OUTPATIENT_ENCOUNTER where SCHEDULED_AT BETWEEN :start_time and :end_time)
