SELECT DISTINCT
t1.ENCOUNTER_ID,
e.CURRENT_DEPT_ID AS "当前科室编码",
o1.ORG_NAME AS "当前科室",
e.FULL_NAME AS "患者姓名",
e.IMRN AS "住院号",
t4.EMPLOYEE_NAME AS "责任医师",
team.ORG_NAME as "TEAM_NAME",
team.ORG_ID as "TEAM_ID",
team.ORG_NO as "TEAM_NO",
team.ORG_NAME as "当前医疗组",
e.ADMITTED_TO_WARD_AT AS "入区时间",
e.DISCHARGED_FROM_WARD_AT AS "出区时间",
t1.CLI_ORDER_TYPE_CODE AS "医嘱类型代码",
t1.ORDER_PERIOD_CODE AS "长期临时医嘱代码",
t1.CLI_ORDER_STATUS AS "医嘱状态",
t1.START_AT AS "长期医嘱开立时间",
t1.TERMINATED_AT AS "长期医嘱终止时间",
CASE
WHEN t1.TERMINATED_AT IS NULL THEN '否'
WHEN DATEDIFF(HOUR, t1.START_AT, t1.TERMINATED_AT) < 24 THEN '是'
ELSE '否'
END AS "是否当日终止",
CASE
WHEN t1.TERMINATED_AT IS NULL THEN 98176
WHEN DATEDIFF(HOUR, t1.START_AT, t1.TERMINATED_AT) < 24 THEN 98175
ELSE 98176
END AS "standFlag"
FROM
INP_CLI_ORDER t1 WITH (NOLOCK)
LEFT JOIN INPATIENT_ENCOUNTER e WITH (NOLOCK) ON t1.ENCOUNTER_ID = e.ENCOUNTER_ID
LEFT JOIN ORGANIZATION o1 WITH (NOLOCK)   ON e.CURRENT_DEPT_ID = o1.ORG_ID
-- 责任医生
 LEFT JOIN INPATIENT_PARTICIPANT t3 WITH (NOLOCK) ON t1.ENCOUNTER_ID = t3.ENCOUNTER_ID AND  t3.IS_DEL = 0 AND  t3.INPAT_PARTICIPANT_TYPE_CODE = 1000098
 LEFT JOIN EMPLOYEE_INFO t4 WITH (NOLOCK) ON t3.EMPLOYEE_ID = t4.EMPLOYEE_ID
LEFT JOIN MRAS_ORGANIZATION team WITH (NOLOCK)  ON team.ORG_ID = e.CURRENT_MEDICAL_GROUP_ID
WHERE
--布局组件设置提升效率
  AND t1.START_AT BETWEEN :start_time and :end_time
AND t1.IS_DEL = '0'
--长期医嘱
AND t1.ORDER_PERIOD_CODE = '138128'
--去掉婴儿类型
AND e.INPAT_ENC_BIZ_TYPE_CODE <> 399552157
--产品规划只去除 已作废，已失效 状态
AND t1.CLI_ORDER_STATUS NOT IN  ('98440','98441')
--去除24小时出入院
AND (e.DISCHARGED_FROM_WARD_AT IS NULL OR DATEDIFF(HOUR, e.FIRST_ADMITTED_TO_WARD_AT, e.DISCHARGED_FROM_WARD_AT) > 24)
