SELECT
t1.ENCOUNTER_ID AS bizId,
'CORE_RESCUE' as eventNo,
'抢救病例' as eventName,
t1.ADMITTED_TO_WARD_AT AS eventAt, -- 预留
GETDATE() AS extractAt,
'1' AS mrasTargetDefinitionId,
'V2.0' AS version,
t1.ENCOUNTER_ID as encounterId,--就诊标识
t1.FULL_NAME AS personName,--姓名
t1.IMRN as imrn,--住院号
t1.CURRENT_DEPT_ID AS currentDeptId,--科室
o1.ORG_NAME AS currentDeptName, --科室名称
t3.EMPLOYEE_ID AS currentAdmitterId,
t4.EMPLOYEE_NAME AS currentAdmitterName,
t1.ADMITTED_TO_WARD_AT AS admittedToWardAt, --入区时间
t1.DISCHARGED_FROM_WARD_AT AS wardDischargedAt, --出区时间
A.EMERGENCY_COUNT as emergencyCount, --抢救次数,
A.EMERGENCY_COUNT_SUCCESS as emergencyCountSuccess, --抢救成功次数
A.HOSPITAL_SOID AS hospitalSoid,
t1.SOURCE_HOSPITAL_AREA_ID AS hospitalAreaId,
CASE WHEN t1.IS_DEL = '1'  THEN 1 ELSE 0 END AS isDel
from MAHP_TREATMENT A
LEFT JOIN MAHP_MAIN B ON A.MAHP_ID = B.MAHP_ID
LEFT JOIN INPATIENT_ENCOUNTER t1 ON B.ENCOUNTER_ID = t1.ENCOUNTER_ID
LEFT JOIN ORGANIZATION o1 ON t1.CURRENT_DEPT_ID = o1.ORG_ID
 -- 责任医生
 LEFT JOIN INPATIENT_PARTICIPANT t3 ON t1.ENCOUNTER_ID = t3.ENCOUNTER_ID AND  t3.IS_DEL = 0 AND  t3.INPAT_PARTICIPANT_TYPE_CODE = 1000098
 LEFT JOIN EMPLOYEE_INFO t4 ON t3.EMPLOYEE_ID = t4.EMPLOYEE_ID
WHERE A.IS_DEL = 0
AND t1.ENCOUNTER_ID IS NOT NULL
AND EMERGENCY_COUNT > 0
