SELECT
    DISTINCT
event.ENCOUNTER_ID ,
event.CURRENT_DEPT_ID AS 当前科室编码,
event.CURRENT_DEPT_NAME AS 当前科室,
event.PERSON_NAME AS 患者姓名,
event.IMRN AS 住院号,
event.CURRENT_ADMITTER_NAME AS 责任医师,
team.ORG_NAME as "TEAM_NAME",
team.ORG_ID as "TEAM_ID",
team.ORG_NO as "TEAM_NO",
team.ORG_NAME as "当前医疗组",
event.ADMITTED_TO_WARD_AT AS 入区时间,
event.WARD_DISCHARGED_AT AS 出区时间,
event.DEATH_AT as 患者死亡时间,
event.FINISH_AT as 死亡讨论记录完成时间,
CASE
WHEN event.DEATH_AT IS NULL OR event.FINISH_AT IS NULL THEN NULL
ELSE DATEDIFF(DAY, event.DEATH_AT, event.FINISH_AT)
  END AS "记录完成时间-死亡时间",
CASE WHEN DEATH_DISCUSSED_IN_DAYS = '98175' THEN '是' ELSE '否' END AS 是否达标,
CASE WHEN DEATH_DISCUSSED_IN_DAYS = '98175' THEN 98175 ELSE 98176 END AS "standFlag"
FROM
MRAS_BUSINESS_DEATH event  #{NOLOCK}
LEFT JOIN INPATIENT_ENCOUNTER inp #{NOLOCK}  ON event.ENCOUNTER_ID = inp.ENCOUNTER_ID
LEFT JOIN MRAS_ORGANIZATION team #{NOLOCK}  ON team.ORG_ID = inp.CURRENT_MEDICAL_GROUP_ID
WHERE
--布局组件设置提升效率
and event.IS_DEL = 0
    AND event.ADMITTED_TO_WARD_AT BETWEEN :marptBeginAt and :marptEndAt
