SELECT
event.ENCOUNTER_ID ,
event.CURRENT_DEPT_ID AS 当前科室编码,
event.CURRENT_DEPT_NAME AS 当前科室,
event.PERSON_NAME AS 患者姓名,
event.IMRN AS 住院号,
event.CURRENT_ADMITTER_NAME AS 责任医师,
team.ORG_NAME as "TEAM_NAME",
team.ORG_ID as "TEAM_ID",
team.ORG_NO as "TEAM_NO",
team.ORG_NAME as "当前医疗组",
event.ADMITTED_TO_WARD_AT AS 入区时间,
event.DISCHARGED_FROM_WARD_AT AS 出区时间,
event.SURG_NAME AS 手术名称,
event.SURG_LEVEL_NAME AS 手术等级,
event.SURGERY_START_AT AS 手术日期,
event.PREOP_MDT_COMPLETED_AT AS 术前多学科会诊记录完成时间,
CASE WHEN event.PREOP_MDT_COMPLETED = 98175 THEN '是' ELSE '否' END AS 是否达标,
CASE WHEN event.PREOP_MDT_COMPLETED = 98175 THEN 98175 ELSE 98176 END AS "standFlag"
FROM
MRAS_BUSINESS_SUR_GRADE event WITH (NOLOCK)
LEFT JOIN INPATIENT_ENCOUNTER inp WITH (NOLOCK)  ON event.ENCOUNTER_ID = inp.ENCOUNTER_ID
LEFT JOIN MRAS_ORGANIZATION team WITH (NOLOCK)  ON team.ORG_ID = inp.CURRENT_MEDICAL_GROUP_ID
WHERE
--布局组件设置提升效率
 event.IS_DEL = 0
AND event.VERSION = 'V2.0'
    AND event.EVENT_AT BETWEEN :marptBeginAt and :marptEndAt
AND event.SURG_LEVEL_CODE = 136619
