-- 死亡病例（死亡记录）
WITH DeathCases AS (
    SELECT
a.ENCOUNTER_ID,
a.HOSPITAL_SOID,
t1.DISCHARGED_FROM_WARD_AT AS DEATH_DATE
    FROM MAHP_DMTS_MAIN a
    INNER JOIN INPATIENT_ENCOUNTER t1 ON a.ENCOUNTER_ID = t1.ENCOUNTER_ID
    WHERE a.DISCHARGE_TYPE_CODE = 136924
AND a.IS_DEL = 0
),
-- 生成 1-30 的数字序列（SQL Server 使用递归 CTE）
DateSequence AS (
    SELECT 1 AS day_offset
    UNION ALL
    SELECT day_offset + 1
    FROM DateSequence
    WHERE day_offset < 30
),
WorkdayCalc AS (
    SELECT
dc.ENCOUNTER_ID,
dc.DEATH_DATE,
dc.HOSPITAL_SOID,
-- 计算第5个工作日
(
SELECT future_date
FROM (
SELECT
DATEADD(DAY, ds.day_offset, dc.DEATH_DATE) AS future_date,
ds.day_offset,
ROW_NUMBER() OVER (ORDER BY ds.day_offset) AS workday_rank
FROM DateSequence ds
WHERE
-- 排除周末（SQL Server 中周日=1,周六=7，取决于 @@DATEFIRST，此处假定默认）
DATEPART(WEEKDAY, DATEADD(DAY, ds.day_offset, dc.DEATH_DATE)) NOT IN (1, 7)
-- 排除节假日
AND NOT EXISTS (
SELECT 1
FROM HOLIDAY h
WHERE h.IS_DEL = 0
AND h.HOSPITAL_SOID = dc.HOSPITAL_SOID
AND CAST(DATEADD(DAY, ds.day_offset, dc.DEATH_DATE) AS DATE)
BETWEEN CAST(h.START_AT AS DATE) AND CAST(h.END_AT AS DATE)
)
) workdays
WHERE workdays.workday_rank = 5
) AS FIFTH_WORKDAY
    FROM DeathCases dc
)
SELECT
    t1.ENCOUNTER_ID AS bizId,  -- 用来更新数据
    'CORE_DEATH' AS eventNo,
    '死亡病例' AS eventName,
    t1.ADMITTED_TO_WARD_AT AS eventAt, -- 预留
    GETDATE() AS extractAt,  -- SQL Server 用 SYSDATETIME() 或 GETDATE()
    '1' AS mrasBusinessIndexId,
    '1' AS mrasTargetDefinitionId,
    'V2.0' AS version,
    t1.ENCOUNTER_ID AS encounterId,
    t1.FULL_NAME AS personName,
    t1.IMRN AS imrn,
    emp.EMPLOYEE_NAME AS currentAdmitterName,
    t1.CURRENT_DEPT_ID AS currentDeptId,
    o1.ORG_NAME AS currentDeptName,
    t1.CURRENT_WARD_ID AS currentWardId,
    o2.ORG_NAME AS currentWardName,
    t1.ADMITTED_TO_WARD_AT AS admittedToWardAt,
    t1.DISCHARGED_FROM_WARD_AT AS wardDischargedAt,
    t1.DISCHARGED_FROM_WARD_AT AS deathAt,
    t2.INP_EMR_SET_CREATED_AT AS FINISH_AT,
    t3.hostEmployeeId AS hostEmployeeId,
    -- 死亡讨论是否5日内完成
    CASE
WHEN t2.INP_EMR_SET_CREATED_AT IS NOT NULL
AND t2.INP_EMR_SET_CREATED_AT <= wc.FIFTH_WORKDAY
THEN 98175
ELSE 98176
    END AS deathDiscussedInDays,
    -- 是否由医务部门组织
    CASE WHEN EXISTS (
SELECT 1
FROM ORGANIZATION_X_EMPLOYEE A
INNER JOIN ORGANIZATION B ON A.ORG_ID = B.ORG_ID AND B.IS_DEL = 0
WHERE A.IS_DEL = 0
AND A.ORGANIZATION_X_EMPLOYEE_TYPE = 399566319
AND (B.ORG_NAME = '医务部' OR B.ORG_NAME = '医务科')
AND A.EMPLOYEE_ID = t3.hostEmployeeId
    ) THEN 98175 ELSE 98176 END AS medicalDeptOrganized,
    -- 是否发生医疗纠纷
    CASE WHEN EXISTS (
SELECT 1
FROM MRAS_MANAGE_COMPLAIN mc
WHERE mc.ENCOUNTER_NO = t1.IMRN
AND mc.IS_DEL = 0
    ) THEN 98175 ELSE 98176 END AS medicalDisputeCase,
    -- 是否由科主任主持
    CASE WHEN t3.hostEmployeeId IS NOT NULL THEN 98175 ELSE 98176 END AS chiefPhysicianChaired,
    NULL AS requiredUploadRecord,
    NULL AS shouldUploadRecord,
    a.HOSPITAL_SOID AS hospitalSoid,
    t1.SOURCE_HOSPITAL_AREA_ID AS hospitalAreaId,
    CASE WHEN a.IS_DEL = 1 THEN 1 ELSE 0 END AS isDel
FROM MAHP_DMTS_MAIN a
LEFT JOIN INPATIENT_ENCOUNTER t1 ON a.ENCOUNTER_ID = t1.ENCOUNTER_ID
LEFT JOIN ORGANIZATION o1 ON t1.CURRENT_DEPT_ID = o1.ORG_ID
LEFT JOIN ORGANIZATION o2 ON t1.CURRENT_WARD_ID = o2.ORG_ID
LEFT JOIN INPATIENT_PARTICIPANT pr ON pr.ENCOUNTER_ID = a.ENCOUNTER_ID
    AND pr.IS_DEL = 0
    AND pr.INPAT_PARTICIPANT_TYPE_CODE = 1000098
LEFT JOIN EMPLOYEE_INFO emp ON pr.EMPLOYEE_ID = emp.EMPLOYEE_ID
    AND emp.IS_DEL = 0
LEFT JOIN (
    SELECT
D.ENCOUNTER_ID,
D.INP_EMR_SET_CREATED_AT
    FROM INP_EMR_SECTION_DATA_ELEMENT A
    LEFT JOIN INPATIENT_EMR_SECTION B ON A.INP_EMR_SECTION_ID = B.INP_EMR_SECTION_ID
AND B.IS_DEL = 0
    LEFT JOIN INPATIENT_EMR_CONTENT C ON C.INP_EMR_CONTENT_ID = B.INP_EMR_CONTENT_ID
AND C.IS_DEL = 0
    LEFT JOIN INPATIENT_EMR_SET D ON D.INP_EMR_RECORD_ID = C.INP_EMR_RECORD_ID
AND D.IS_DEL = 0
    WHERE A.IS_DEL = 0
AND D.INP_EMR_SET_TITLE = '死亡病例讨论记录'
AND A.INP_EMR_DATA_ELEMENT_WIN_ID = '399301329' -- 讨论日期
) t2 ON t2.ENCOUNTER_ID = t1.ENCOUNTER_ID
LEFT JOIN (
    SELECT
D.ENCOUNTER_ID,
CASE
WHEN A.INP_EMR_DATA_ELEMENT_VALUE IS NOT NULL
THEN A.CREATED_BY
ELSE NULL
END AS hostEmployeeId
    FROM INP_EMR_SECTION_DATA_ELEMENT A
    LEFT JOIN INPATIENT_EMR_SECTION B ON A.INP_EMR_SECTION_ID = B.INP_EMR_SECTION_ID
    LEFT JOIN INPATIENT_EMR_CONTENT C ON C.INP_EMR_CONTENT_ID = B.INP_EMR_CONTENT_ID
    LEFT JOIN INPATIENT_EMR_SET D ON D.INP_EMR_RECORD_ID = C.INP_EMR_RECORD_ID
    WHERE D.INP_EMR_SET_TITLE = '死亡病例讨论记录'
AND A.INP_EMR_DATA_ELEMENT_WIN_ID = '399336516' -- 病例讨论主持人姓名
) t3 ON t3.ENCOUNTER_ID = t1.ENCOUNTER_ID
LEFT JOIN WorkdayCalc wc ON a.ENCOUNTER_ID = wc.ENCOUNTER_ID
WHERE a.DISCHARGE_TYPE_CODE = 136924
    AND a.IS_DEL = 0
-- 后续的 ETC 占位符请根据实际需要取消注释并替换为有效的条件
AND a.ENCOUNTER_ID in (select ENCOUNTER_ID from INPATIENT_ENCOUNTER where DISCHARGED_FROM_WARD_AT BETWEEN :start_time and :end_time)
