SELECT
event.ENCOUNTER_ID ,
event.CURRENT_DEPT_ID AS 当前科室编码,
event.CURRENT_DEPT_NAME AS 当前科室,
event.IMRN AS 住院号,
event.PERSON_NAME AS 患者姓名,
event.CURRENT_ADMITTER_NAME AS 责任医师,
team.ORG_NAME as "TEAM_NAME",
team.ORG_ID as "TEAM_ID",
team.ORG_NO as "TEAM_NO",
team.ORG_NAME as "当前医疗组",
event.ADMITTED_TO_WARD_AT AS 入区时间,
event.WARD_DISCHARGED_AT AS 出区时间,
event.CRITICAL_VAL_DTL as 危急值详情,
emp3.EMPLOYEE_NAME as 危急值发布人,
event.RECEIVE_TIME as 危急值接收时间,
emp1.EMPLOYEE_NAME as 危急值接收人,
event.PROCESS_TIME as 危急值处置时间,
emp2.EMPLOYEE_NAME as 处置人,
CASE
WHEN event.PROCESS_TIME IS NULL THEN NULL  -- 如果未处置，返回NULL
ELSE DATEDIFF(HOUR, event.RECEIVE_TIME, event.PROCESS_TIME)  -- 计算小时差
END AS "危急值处置时间-危急值接收时间（小时）",
CASE WHEN CV_COMPLETED = '98175' THEN '是' ELSE '否' END AS 是否当日处置,
CASE WHEN CV_COMPLETED = '98175' THEN '是' ELSE '否' END AS 是否达标,
CASE WHEN CV_COMPLETED = '98175' THEN 98175 ELSE 98176 END AS "standFlag"
FROM
MRAS_BUSINESS_CRITICAL_RPT event  WITH (NOLOCK)
LEFT JOIN INPAT_TRANSFER t1  WITH (NOLOCK)  ON event.ENCOUNTER_ID = t1.ENCOUNTER_ID
LEFT JOIN ORGANIZATION o1  WITH (NOLOCK)   ON t1.ORIGIN_DEPT_ID = o1.ORG_ID
LEFT JOIN ORGANIZATION o2  WITH (NOLOCK)  ON t1.DESTINATION_DEPT_ID = o2.ORG_ID
LEFT JOIN EMPLOYEE_INFO emp1   WITH (NOLOCK)  ON event.RECEIVE_BY = emp1.EMPLOYEE_ID
LEFT JOIN EMPLOYEE_INFO emp2   WITH (NOLOCK)  ON event.PROCESS_BY = emp2.EMPLOYEE_ID
LEFT JOIN EMPLOYEE_INFO emp3 WITH (NOLOCK)  ON event.REPORT_BY = emp3.EMPLOYEE_ID
LEFT JOIN INPATIENT_ENCOUNTER inp WITH (NOLOCK)  ON event.ENCOUNTER_ID = inp.ENCOUNTER_ID
LEFT JOIN MRAS_ORGANIZATION team WITH (NOLOCK)  ON team.ORG_ID = inp.CURRENT_MEDICAL_GROUP_ID
WHERE
--布局组件设置提升效率
AND event.ADMITTED_TO_WARD_AT BETWEEN :start_time and :end_time
