SELECT
event.ENCOUNTER_ID ,
event.CURRENT_DEPT_ID AS '当前科室编码',
event.CURRENT_DEPT_NAME AS '当前科室',
event.PERSON_NAME AS '患者姓名',
event.IMRN AS '住院号',
event.CURRENT_ADMITTER_NAME AS '责任医师',
team.ORG_NAME as "TEAM_NAME",
team.ORG_ID as "TEAM_ID",
team.ORG_NO as "TEAM_NO",
team.ORG_NAME as "当前医疗组",
event.ADMITTED_TO_WARD_AT AS '入区时间',
event.DISCHARGED_FROM_WARD_AT AS '出区时间',
event.OP_NAME AS '手术名称',
event.SURGERY_LEVEL_NAME AS '手术等级',
event.SURGERY_END_AT as '手术完成时间',
event.PRE_OP_DISC_AT as '术前讨论记录完成时间',
CASE WHEN PREOP_DISC_COMPLETE = 98175 THEN '是' ELSE '否' END AS '是否达标',
CASE WHEN PREOP_DISC_COMPLETE = 98175 THEN 98175 ELSE 98176 END AS "standFlag"
FROM
MRAS_BUSINESS_OP_DISC event  WITH (NOLOCK)
LEFT JOIN INPATIENT_ENCOUNTER inp WITH (NOLOCK)  ON event.ENCOUNTER_ID = inp.ENCOUNTER_ID
LEFT JOIN MRAS_ORGANIZATION team WITH (NOLOCK)  ON team.ORG_ID = inp.CURRENT_MEDICAL_GROUP_ID
WHERE
--布局组件设置提升效率
 event.VERSION = 'V2.0'
    AND event.SURGERY_END_AT BETWEEN :marptBeginAt and :marptEndAt
AND event.SURGERY_CLASS_CODE != 138380
