SELECT
event.ENCOUNTER_ID ,
event.CURRENT_DEPT_ID AS 当前科室编码,
event.CURRENT_DEPT_NAME AS 当前科室,
event.PERSON_NAME AS 患者姓名,
event.IMRN AS 住院号,
event.CURRENT_ADMITTER_NAME AS 责任医师,
team.ORG_NAME as "TEAM_NAME",
team.ORG_ID as "TEAM_ID",
team.ORG_NO as "TEAM_NO",
team.ORG_NAME as "当前医疗组",
event.ADMITTED_TO_WARD_AT AS 入区时间,
event.WARD_DISCHARGED_AT AS 出区时间,
event.FINISH_AT as 死亡病例讨论记录完成时间,
emp1.EMPLOYEE_NAME as 死亡病例讨论主持人,
CASE WHEN MEDICAL_DEPT_ORGANIZED = '98175' THEN '是' ELSE '否' END AS 是否医务科主持,
CASE WHEN MEDICAL_DEPT_ORGANIZED = '98175' THEN 98175 ELSE 98176 END AS "standFlag"
FROM
MRAS_BUSINESS_DEATH event  WITH (NOLOCK)
LEFT JOIN EMPLOYEE_INFO emp1  WITH (NOLOCK)  ON emp1.EMPLOYEE_ID = event.HOST_EMPLOYEE_ID
LEFT JOIN INPATIENT_ENCOUNTER inp WITH (NOLOCK)  ON event.ENCOUNTER_ID = inp.ENCOUNTER_ID
LEFT JOIN MRAS_ORGANIZATION team WITH (NOLOCK)  ON team.ORG_ID = inp.CURRENT_MEDICAL_GROUP_ID
WHERE
--布局组件设置提升效率
and event.IS_DEL = 0
    AND event.ADMITTED_TO_WARD_AT BETWEEN :start_time and :end_time
