"""Mechanically derive the embedded SQLite schema from the legacy MySQL schema."""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "scripts" / "init_runtime_db.sql"
TARGET = ROOT / "backend-java" / "src" / "main" / "resources" / "sqlite-runtime-schema.sql"
PYTHON_TARGET = ROOT / "scripts" / "init_runtime_sqlite.sql"


def convert_definition(value: str) -> str:
    value = re.sub(
        r"\bBIGINT\s+PRIMARY\s+KEY\s+AUTO_INCREMENT\b",
        "INTEGER PRIMARY KEY AUTOINCREMENT",
        value,
        flags=re.I,
    )
    value = re.sub(r"\bAUTO_INCREMENT\b", "", value, flags=re.I)
    value = re.sub(r"\b(?:LONGTEXT|MEDIUMTEXT|CLOB|JSON|DATETIME|TIMESTAMP)\b", "TEXT", value, flags=re.I)
    value = re.sub(r"\bTINYINT\b", "INTEGER", value, flags=re.I)
    value = re.sub(r"\bDECIMAL\([^)]*\)", "REAL", value, flags=re.I)
    value = re.sub(r"\s+", " ", value).strip().rstrip(",")
    return value


def build() -> str:
    lines = SOURCE.read_text(encoding="utf-8-sig").splitlines()
    output = ["-- Generated by scripts/build_sqlite_runtime_schema.py. Do not edit by hand.", ""]
    indexes: list[str] = []
    index_names: set[str] = set()
    position = 0
    while position < len(lines):
        match = re.match(r"CREATE TABLE IF NOT EXISTS\s+([A-Za-z0-9_]+)\s*\(", lines[position].strip(), re.I)
        if not match:
            position += 1
            continue
        table = match.group(1)
        position += 1
        definitions: list[str] = []
        while position < len(lines):
            raw = lines[position].strip()
            if raw.startswith(");") or raw.startswith(") ENGINE"):
                break
            if not raw:
                position += 1
                continue
            statement = raw
            if re.match(r"(?:UNIQUE\s+KEY|KEY|INDEX)\b", statement, re.I):
                while ("(" not in statement or statement.count("(") > statement.count(")")) and position + 1 < len(lines):
                    position += 1
                    statement += " " + lines[position].strip()
                unique_match = re.match(r"UNIQUE\s+KEY\s+\S+\s*\((.*)\)\s*,?$", statement, re.I)
                index_match = re.match(r"(?:KEY|INDEX)\s+(\S+)\s*\((.*)\)\s*,?$", statement, re.I)
                if unique_match:
                    definitions.append(f"UNIQUE ({unique_match.group(1)})")
                elif index_match:
                    base_name = re.sub(r"[^A-Za-z0-9_]", "_", index_match.group(1).strip("`"))
                    name = base_name if base_name not in index_names else f"{table}_{base_name}"
                    index_names.add(name)
                    indexes.append(f"CREATE INDEX IF NOT EXISTS {name} ON {table} ({index_match.group(2)});")
            else:
                definitions.append(convert_definition(statement))
            position += 1
        output.append(f"CREATE TABLE IF NOT EXISTS {table} (")
        output.extend(
            f"  {definition}{',' if index < len(definitions) - 1 else ''}"
            for index, definition in enumerate(definitions)
        )
        output.extend([");", ""])
        position += 1

    output.extend(indexes)
    output.extend(
        [
            "",
            "CREATE TABLE IF NOT EXISTS med_agent_java_message (",
            "  id INTEGER PRIMARY KEY AUTOINCREMENT,",
            "  session_key TEXT NOT NULL,",
            "  hospital_id TEXT NOT NULL,",
            "  user_id TEXT NOT NULL,",
            "  role TEXT NOT NULL,",
            "  content TEXT NOT NULL,",
            "  rule_id TEXT,",
            "  rule_name TEXT,",
            "  stat_start TEXT,",
            "  stat_end TEXT,",
            "  run_id TEXT,",
            "  upload_file_key TEXT,",
            "  created_at TEXT NOT NULL",
            ");",
            "CREATE INDEX IF NOT EXISTS idx_java_message_session ON med_agent_java_message(session_key, id);",
            "",
        ]
    )
    return "\n".join(output)


if __name__ == "__main__":
    content = build()
    TARGET.write_text(content, encoding="utf-8")
    PYTHON_TARGET.write_text(content, encoding="utf-8")
    print(TARGET)
    print(PYTHON_TARGET)
