from __future__ import annotations

from enum import Enum


class FailureClass(str, Enum):
    SEMANTIC_PLAN_ERROR = "semantic_plan_error"
    TASK_TYPE_ERROR = "task_type_error"
    USER_GOAL_CHANGED = "user_goal_changed"
    ALTERNATIVE_DIRECTION_AVAILABLE = "alternative_direction_available"
    USER_CLARIFICATION_REQUIRED = "user_clarification_required"
    DATABASE_ERROR = "database_error"
    PERMISSION_ERROR = "permission_error"
    OBJECT_EXPIRED = "object_expired"
    EVIDENCE_CONFLICT = "evidence_conflict"
    TOOL_ERROR = "tool_error"
    UNKNOWN = "unknown"


_FAILURE_CLASSES = {
    "PLAN_INTENT_MISMATCH": FailureClass.SEMANTIC_PLAN_ERROR,
    "TASK_TYPE_MISMATCH": FailureClass.TASK_TYPE_ERROR,
    "USER_GOAL_CHANGED": FailureClass.USER_GOAL_CHANGED,
    "ASSUMPTION_INVALID_ALTERNATIVE_AVAILABLE": FailureClass.ALTERNATIVE_DIRECTION_AVAILABLE,
    "INDICATOR_AMBIGUOUS": FailureClass.USER_CLARIFICATION_REQUIRED,
    "TARGET_INDICATOR_AMBIGUOUS": FailureClass.USER_CLARIFICATION_REQUIRED,
    "TIME_RANGE_AMBIGUOUS": FailureClass.USER_CLARIFICATION_REQUIRED,
    "STAT_PERIOD_MISSING": FailureClass.USER_CLARIFICATION_REQUIRED,
    "DATABASE_ACCESS_CONFLICT": FailureClass.DATABASE_ERROR,
    "DATABASE_UNAVAILABLE": FailureClass.DATABASE_ERROR,
    "TRIAL_RUN_FAILED": FailureClass.DATABASE_ERROR,
    "PERMISSION_DENIED": FailureClass.PERMISSION_ERROR,
    "PATIENT_DETAIL_FORBIDDEN": FailureClass.PERMISSION_ERROR,
    "SQL_OBJECT_EXPIRED": FailureClass.OBJECT_EXPIRED,
    "SQL_CHAIN_INCONSISTENT": FailureClass.EVIDENCE_CONFLICT,
    "SQL_PERIOD_INCONSISTENT": FailureClass.EVIDENCE_CONFLICT,
    "NUMERIC_RESULT_INCONSISTENT": FailureClass.EVIDENCE_CONFLICT,
    "EVIDENCE_HOSPITAL_MISMATCH": FailureClass.EVIDENCE_CONFLICT,
    "EVIDENCE_SUBTASK_MISMATCH": FailureClass.EVIDENCE_CONFLICT,
    "EVIDENCE_RULE_MISMATCH": FailureClass.EVIDENCE_CONFLICT,
    "EVIDENCE_PERIOD_MISMATCH": FailureClass.EVIDENCE_CONFLICT,
    "EVIDENCE_SQL_MISMATCH": FailureClass.EVIDENCE_CONFLICT,
    "EVIDENCE_LEGACY_RESULT_MISSING": FailureClass.EVIDENCE_CONFLICT,
    "EVIDENCE_PAYLOAD_MISMATCH": FailureClass.EVIDENCE_CONFLICT,
    "EVIDENCE_EXPIRED": FailureClass.OBJECT_EXPIRED,
    "TOOL_TIMEOUT": FailureClass.TOOL_ERROR,
    "TOOL_EXECUTION_FAILED": FailureClass.TOOL_ERROR,
}


def classify_failure(code: str) -> FailureClass:
    return _FAILURE_CLASSES.get(str(code or ""), FailureClass.UNKNOWN)
