SELECT
e2.ENCOUNTER_ID,
pro.MEDTECH_PRO_NO AS "新技术项目编码",
pro.MEDTECH_PRO_NAME AS "新技术项目名称",
pro.CREATED_AT AS "新技术项目新增时间",
'是' AS "第四年是否开展",
p2.CURRENT_DEPT_NAME AS "当前科室",
p2.PERSON_NAME AS "患者姓名",
e2.IMRN AS "住院号",
t4.EMPLOYEE_NAME AS "责任医师",
team.ORG_NAME as "TEAM_NAME",
team.ORG_ID as "TEAM_ID",
team.ORG_NO as "TEAM_NO",
team.ORG_NAME as "当前医疗组",
e2.ADMITTED_TO_WARD_AT AS "入区时间",
e2.DISCHARGED_FROM_WARD_AT AS "出区时间",
98175 AS "standFlag"
FROM
    MRAS_MEDTECH_PRO pro
LEFT JOIN MRAS_MEDTECH_PROC p2 ON p2.MRAS_MEDTECH_PRO_ID = pro.MRAS_MEDTECH_PRO_ID  AND p2.IS_DEL = 0
LEFT JOIN INPATIENT_ENCOUNTER e2 ON p2.ENCOUNTER_ID = e2.ENCOUNTER_ID
-- 责任医生
LEFT JOIN INPATIENT_PARTICIPANT t3 ON e2.ENCOUNTER_ID = t3.ENCOUNTER_ID AND  t3.IS_DEL = 0 AND  t3.INPAT_PARTICIPANT_TYPE_CODE = 1000098
LEFT JOIN EMPLOYEE_INFO t4 ON t3.EMPLOYEE_ID = t4.EMPLOYEE_ID
LEFT JOIN MRAS_ORGANIZATION team WITH (NOLOCK)  ON team.ORG_ID = e2.CURRENT_MEDICAL_GROUP_ID
WHERE
--布局组件设置提升效率
    AND pro.IS_DEL = 0
    AND DATEADD(YEAR, 2, pro.CREATED_AT) >= :start_time
AND DATEADD(YEAR, 1, pro.CREATED_AT) <= :end_time
AND p2.CREATED_AT BETWEEN :start_time AND :end_time
