SELECT
event.ENCOUNTER_ID ,
event.DEPT_ID AS "当前科室编码",
event.DEPT_NAME AS "当前科室",
event.IMRN AS "住院号",
event.PERSON_NAME AS "患者姓名",
event.EMPLOYEE_NAME AS "责任医师",
team.ORG_NAME as "TEAM_NAME",
team.ORG_ID as "TEAM_ID",
team.ORG_NO as "TEAM_NO",
team.ORG_NAME as "当前医疗组",
event.ADMITTED_TO_WARD_AT AS "入区时间",
event.DISCHARGED_FROM_WARD_AT AS "出区时间",
event.ANTI_MEDICINE_NAME AS "特殊级抗菌药名称",
event.PRESCRIBED_AT AS "医嘱开立时间",
event.REGISTER_FINISH_AT AS "会诊记录完成时间",
event.REGISTER_ANTI_MEDICINE_NAME AS "会诊记录抗菌药名称",
CASE WHEN APPROVAL_ANTI = '98175' THEN '是' ELSE '否' END AS "医嘱和会诊记录药品是否一致",
CASE WHEN APPROVAL_ANTI = '98175' THEN 98175 ELSE 98176 END AS "standFlag"
FROM
MRAS_BUSINESS_ANTI event  WITH (NOLOCK)
LEFT JOIN INPATIENT_ENCOUNTER inp WITH (NOLOCK)  ON event.ENCOUNTER_ID = inp.ENCOUNTER_ID
LEFT JOIN MRAS_ORGANIZATION team WITH (NOLOCK)  ON team.ORG_ID = inp.CURRENT_MEDICAL_GROUP_ID
WHERE
--布局组件设置提升效率
  AND event.PRESCRIBED_AT BETWEEN :start_time and :end_time
AND APPROVAL_ANTI = '98175'
