SELECT t1.ENCOUNTER_ID
AS bizId,
--用来更新数据
t1.FIRST_ADMITTED_TO_WARD_AT
AS eventAt,
-- 预留
'1' AS mrasTargetDefinitionId,
'V2.0' as version,
GETDATE()
AS extractAt,
t1.ENCOUNTER_ID
AS encounterId,
t1.FULL_NAME
AS personName,
t1.IMRN
as imrn,
t1.CURRENT_DEPT_ID
AS currentDeptId,
o1.ORG_NAME
AS currentDeptName,
t1.CURRENT_WARD_ID
AS currentWardId,
o2.ORG_NAME
AS currentWardName,
t1.FIRST_ADMITTED_TO_WARD_AT
AS admittedToWardAt,
t1.DISCHARGED_FROM_WARD_AT
AS wardDischargedAt,
t3.EMPLOYEE_ID
AS currentAdmitterId,
t4.EMPLOYEE_NAME
AS currentAdmitterName,
t1.HOSPITAL_SOID
AS hospitalSoid,
t1.SOURCE_HOSPITAL_AREA_ID
AS hospitalAreaId,
t5.PLANNED_SURGERY_AT
AS unPlannedSurgeryAt,--非计划手术时间
t5.SURGERY_LEVEL_CODE
AS surgeryLevelCode,--手术级别
t6.CREATED_AT
AS emrCreatedAt,--疑难病历讨论时间
t6.INP_EMR_SET_CREATED_AT
AS emrSetSubmitAt,--疑难病历讨论提交时间
case when t2.ENCOUNTER_ID is not null and C.READM_PLAN_WITHIN_MONTH_NO=1 then 98175 else 98176 end AS unPlanedAdmitted,--非计划再次入院
CASE WHEN t1.IS_DEL = '1' THEN 1 ELSE 0 END
AS isDel,
CASE
WHEN t6.INP_EMR_SET_ID IS NOT NULL THEN 98175
ELSE 98176 END
AS unplannedDifficultDiscussion,--非计划手术患者疑难病历讨论
''
AS memo
FROM INPATIENT_ENCOUNTER t1
left join INPATIENT_ENCOUNTER t2
on t1.PERSON_ID = t2.PERSON_ID and datediff(day, t1.ADMITTED_TO_WARD_AT, t2.ADMITTED_TO_WARD_AT) < 31
and t1.ENCOUNTER_ID <> t2.ENCOUNTER_ID
left join (SELECT A.*,
B.PLANNED_SURGERY_AT,
B.SURGERY_LEVEL_CODE,
C.CS_NAME,
ROW_NUMBER() OVER (PARTITION BY A.ENCOUNTER_ID ORDER BY A.PRESCRIBED_AT DESC ) AS rn
FROM INP_CLI_ORDER A
INNER JOIN INP_SURGICAL_PLAN B ON
B.CLI_ORDER_ID = A.CLI_ORDER_ID
inner join INP_CLI_ORDER_ITEM C on C.CLI_ORDER_ID = A.CLI_ORDER_ID
left join CLINICAL_SERVICE_SURGERY D on C.CS_ID = D.CS_ID
AND B.UNPLANNED_REOPERATION_FLAG = 98175
AND B.PLANNED_SURGERY_DATE IS NOT NULL
WHERE A.IS_DEL = 0
and B.IS_DEL = 0
and D.SURGERY_TYPE_CODE in (957347, 957348)
AND A.CLI_ORDER_TYPE_CODE = 256200) t5 ON t1.ENCOUNTER_ID = t5.ENCOUNTER_ID and t5.rn = 1
left join (select A.*, ROW_NUMBER() OVER (PARTITION BY A.ENCOUNTER_ID ORDER BY A.CREATED_AT DESC ) AS rn
from INPATIENT_EMR_SET A
where A.IS_DEL = 0
and A.INP_MRT_MONITOR_ID = 125044678493294634) t6
on t1.ENCOUNTER_ID = t6.ENCOUNTER_ID and t6.rn = 1
left JOIN MAHP_MAIN B ON t1.ENCOUNTER_ID = B.ENCOUNTER_ID AND B.MAHP_STATUS = 958566 AND B.IS_DEL = 0
INNER JOIN MAHP_QC C ON C.MAHP_ID = B.MAHP_ID AND C.IS_DEL = 0
LEFT JOIN ORGANIZATION o1 ON t1.CURRENT_DEPT_ID = o1.ORG_ID
LEFT JOIN ORGANIZATION o2 ON t1.CURRENT_WARD_ID = o2.ORG_ID
LEFT JOIN INPATIENT_PARTICIPANT t3
ON t1.ENCOUNTER_ID = t3.ENCOUNTER_ID AND t3.IS_DEL = 0 AND t3.INPAT_PARTICIPANT_TYPE_CODE = 1000098
LEFT JOIN EMPLOYEE_INFO t4 ON t3.EMPLOYEE_ID = t4.EMPLOYEE_ID
left join VALUE_SET v on t5.SURGERY_LEVEL_CODE = v.VALUE_ID
WHERE t1.IS_DEL = 0
 and ((t2.ENCOUNTER_ID is not null and C.READM_PLAN_WITHIN_MONTH_NO=1) or t5.ENCOUNTER_ID is not null)
 AND t1.ENCOUNTER_ID in (select ENCOUNTER_ID from INPATIENT_ENCOUNTER where DISCHARGED_FROM_WARD_AT BETWEEN :startTime and :endTime)
