SELECT
event.ENCOUNTER_ID ,
event.DEPT_ID AS '当前科室编码',
event.DEPT_NAME AS '当前科室',
event.IMRN AS '住院号',
event.PERSON_NAME AS '患者姓名',
event.EMPLOYEE_NAME AS '责任医师',
team.ORG_NAME as "TEAM_NAME",
team.ORG_ID as "TEAM_ID",
team.ORG_NO as "TEAM_NO",
team.ORG_NAME as "当前医疗组",
event.ADMITTED_TO_WARD_AT AS '入区时间',
event.DISCHARGED_FROM_WARD_AT AS '出区时间',
event.SURGERY_NAME AS '手术名称',
event.SURGERY_START_AT AS '手术开始时间',
event.SURGERY_END_AT AS '手术结束时间',
CASE WHEN ANES_DOCT_OVERLAP = '98175' THEN '是' ELSE '否' END AS '麻醉医师手术时间是否重合',
CASE WHEN ANES_DOCT_OVERLAP = '98175' THEN 98175 ELSE 98176 END AS "standFlag",
t11.SURGERY_NAME AS '重合手术名称',
t12.SURGERY_START_AT AS '重合手术开始时间',
t12.SURGERY_END_AT AS '重合手术结束时间'
FROM
MRAS_BUSINESS_SURGERY event  WITH (NOLOCK)
LEFT JOIN (
SELECT
t.CLI_ORDER_ITEM_ID,
STUFF((
SELECT ',' + t2.SURGERY_NAME
FROM (
SELECT DISTINCT isa.CLI_ORDER_ITEM_ID, isa.SURGERY_NAME
FROM INP_SURGICAL_ANESTHESIA_PLAN isa WITHWITH (NOLOCK)
WHERE isa.IS_DEL = 0 AND isa.SURGERY_NAME IS NOT NULL AND isa.CLI_ORDER_ITEM_ID IS NOT NULL
) t2
WHERE t2.CLI_ORDER_ITEM_ID = t.CLI_ORDER_ITEM_ID
FOR XML PATH('')
), 1, 1, '') AS SURGERY_NAME,
MAX(t.SURGICAL_ANESTHESIA_CODE) AS ANES_TYPE_ID
FROM (
SELECT DISTINCT isa.CLI_ORDER_ITEM_ID, isa.SURGERY_NAME, isa.SURGICAL_ANESTHESIA_CODE
FROM INP_SURGICAL_ANESTHESIA_PLAN isa
WHERE isa.IS_DEL = 0 AND isa.SURGERY_NAME IS NOT NULL AND isa.CLI_ORDER_ITEM_ID IS NOT NULL
) t
GROUP BY t.CLI_ORDER_ITEM_ID
) t11 on event.OVERLAP_ANES_DOCT_SURGERIES = t11.CLI_ORDER_ITEM_ID
LEFT JOIN INP_SURGICAL_PLAN t12 on t12.CLI_ORDER_ITEM_ID = t11.CLI_ORDER_ITEM_ID
LEFT JOIN INPATIENT_ENCOUNTER inp WITH (NOLOCK)  ON event.ENCOUNTER_ID = inp.ENCOUNTER_ID
LEFT JOIN MRAS_ORGANIZATION team WITH (NOLOCK)  ON team.ORG_ID = inp.CURRENT_MEDICAL_GROUP_ID
WHERE
--布局组件设置提升效率
   event.SURGERY_END_AT BETWEEN :marptBeginAt and :marptEndAt
